import Logo from "../assets/svg/kingfloki-logo.svg"
import FooterLogoSvg from '../assets/svg/footerlogo.svg';
import GitbookIcon from '../assets/svg/iconboxgitbook.svg';
import MediumIcon from '../assets/svg/iconboxmedium.svg';
import TelegramIcon from '../assets/svg/iconboxtg.svg';
import TwitterIcon from '../assets/svg/iconboxtwitter.svg';
import YoutubeIcon from '../assets/svg/iconboxyt.svg';
import WearableBg from '../assets/png/landing/header-bg.png'
import KingFloki3D from '../assets/png/landing/kingfloki3D.png'
import NftGamesSvg from '../assets/svg/nft-games.svg'
import EthereumSvg from '../assets/svg/ethereum.svg'
import CharactersPng from '../assets/png/landing/characters.png'
import FloatingCard from '../assets/png/landing/floating-cards.png'
import FloatingCardMobile from '../assets/png/landing/floating-cards-mobile.png'
import MintCardGif from "../assets/gif/mint-gif.gif"
import NFTCarouselImg from '../assets/png/landing/carousel.png'
import RaityGif from '../assets/gif/raity-gif.gif'
import CharacterGroup from '../assets/png/landing/groupage.png'
import GradientRarity from '../assets/png/landing/gradient-rarity.png'
import TradeOpenseaImg from '../assets/png/landing/trade-on-opensea.png'
import PotionBox from '../assets/png/landing/potion-box.png'
import OpenseaLogo from '../assets/svg/opensea-logo.svg'
import BgBottom from '../assets/png/landing/bg-bottom.png'
import EbmKFVideo1 from '../assets/video/KF-Website-1-vp9-chrome.webm'
import KFVideo1 from '../assets/video/KF-Website-1.mp4'
import MobKFVideo1 from '../assets/video/KF-Website-1-MOB.mp4'
import EbmMobKFVideo1 from '../assets/video/KF-Website-1-MOB-vp9-chrome.webm'
import KFVideo2 from '../assets/video/KF-Website-2.mp4'
import MobKFVideo2 from '../assets/video/KF-Website-2-MOB.mp4'
import KFVideo3 from '../assets/video/KF-Website-3.mp4'
import EbmKFVideo3 from '../assets/video/KF-Website-3-vp9-chrome.webm'
import MobKFVideo3 from '../assets/video/KF-Website-3-MOB.mp4'
import NavTwitterIcon from "../assets/svg/menu_icon-01.svg"
import NavTelegramIcon from "../assets/svg/menu_icon-02.svg"
import NavDiscordIcon from "../assets/svg/menu_icon-03.svg"
import NavOpenseaIcon from "../assets/svg/menu_icon-04.svg"
import DiscordIcon from '../assets/svg/discord.svg'

// Wearable
import DeskIslandPng from '../assets/png/wearable/island.png'
import MobIslandPng from '../assets/png/wearable/mobile/island_MOBILE.png'
import DeskKingFlokiVideo from '../assets/video/kingfloki-video1.mp4'
import MobKingFlokiVideo from '../assets/video/kingfloki-video1MOB.mp4'
import KFVideo4 from '../assets/video/KF-Website-4.mp4'
import EbmKFVideo4 from '../assets/video/KF-Website-4-vp9-chrome.webm'
import OutnowPng from "../assets/svg/outnow.svg"
import FloadingCard from "../assets/png/wearable/floating-cards-cut.png"
import KFRunVisual from "../assets/png/wearable/KF-Run-visual.png"
import KFCompetition from '../assets/png/wearable/KF-competition.png'
import DeskDiveWorldPng from "../assets/png/wearable/desk-dive.png"
import LoaderVideo from "../assets/video/Loader-hevc-safari.mp4"
import EbmLoaderVideo from "../assets/video/Loader-vp9-chrome.webm"
import TopVideo from '../assets/video/topVideo.mp4'
import TopVideoMob from '../assets/video/topVideoMOB.mp4'

export { Logo, FooterLogoSvg, GitbookIcon, MediumIcon, TelegramIcon, TwitterIcon, YoutubeIcon, WearableBg, KingFloki3D, NftGamesSvg, EthereumSvg, CharactersPng, FloatingCard, FloatingCardMobile, MintCardGif, NFTCarouselImg, RaityGif, CharacterGroup, GradientRarity, TradeOpenseaImg, PotionBox, OpenseaLogo, BgBottom, KFVideo1, MobKFVideo1, KFVideo2, MobKFVideo2, KFVideo3, MobKFVideo3, NavDiscordIcon, NavOpenseaIcon, NavTwitterIcon, NavTelegramIcon, EbmKFVideo1, EbmMobKFVideo1, EbmKFVideo3, DeskIslandPng, MobIslandPng, DeskKingFlokiVideo, MobKingFlokiVideo, KFVideo4, EbmKFVideo4, OutnowPng, FloadingCard, KFRunVisual, KFCompetition, DeskDiveWorldPng, LoaderVideo, EbmLoaderVideo ,TopVideo, TopVideoMob, DiscordIcon}